### ISSUE TITLE
checkin policy is not satisfied even after closing the code review request ,any idea ?  

### ISSUE THREAD

**Issue by kriskoneru** [colindembovsky/ColinsALMCornerCheckinPolicies#10]
I had installed the checkin policy on VS 2015. Before i did a checkin it asked to submit for a code review. I did submit for a code review to one of my other colleague.. he then went and approved my changes. So the code review is done. I went in and tried to checkin the same file but it still shows that the code review is not yet done.

**Comment by colindembovsky** [comment]
Hi @kriskoneru Have you configured the "Require Code review to be closed" setting? If this is set, then even if the code review is complete, the policy may require that the code review work item state is set to closed (which it doesn't do by when you approve / reject the code review in VS).

**Comment by kriskoneru** [comment]
Ok.. thank you yes previously i did set check the option for "Require Code reivew to be closed". Now when i unchecked the option. i am able to checkin once the code review is complete.

**Comment by colindembovsky** [comment]
Glad you got it sorted!
