### ISSUE TITLE
CheckinPolicy - bottom 4 buttons hidden...

### ISSUE THREAD

**Issue by Walruswal** [colindembovsky/ColinsALMCornerCheckinPolicies#11]
Hi - when using this, there are 4 buttons at the bottom of the ode review Policy settings that can't be seen properly... Visual Studio 2017
![image](https://user-images.githubusercontent.com/22956992/27686801-3b79e3b4-5ccc-11e7-8e9b-913d0f852fd9.png)

Cheers

Warren

**Comment by jmelosegui** [comment]
Maybe related to #9

**Comment by tekkenxpert** [comment]
Hi @jmelosegui 

I am having this same issue, but am not understanding the resolution in #9 
Can you provide the updated VSIX package?

**Comment by PaytonWu** [comment]
I met the same issue when I was trying to resolve #9 .  You need to clone this repro, update the code and generate the .vsix package yourself with the DLLs located under your VS foler (for example, on my PC, it is "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer".  Just pick those DLLs contained in the original .vsix file.)  I cannot provide the updated .vsix file,  as I just verified and found my previous local updated .vsix ( for solving #9 ) doesn't resolve this issue on my 4K resolution PC.

**Comment by colindembovsky** [comment]
Closed in release [3.15](https://marketplace.visualstudio.com/items?itemName=ColinD.ColinsALMCheckinPoliciesVS2017)

**Comment by me3rag** [comment]
I am still facing the issue #11 "CheckinPolicy - bottom 4 buttons hidden",
I am using VS 2017 community v. 15.5.2. and install the extension with the version 3.15
I am also unable to resize the height of the windows

![buttons cutoff](https://user-images.githubusercontent.com/6468742/35224615-3f24a9bc-ff8e-11e7-81ef-ad31c83dea7f.JPG)


I also tries to get the latest DLL version of the 'Microsoft.TeamFoundation.VersionControl.Common' and it is 15.111.26008.0 but this DLL'Microsoft.TeamFoundation.VersionControl.Controls.Common' has the version # 14.102.25619.0
