### ISSUE TITLE
Not able to Associate the Code Review workitem which is completed

### ISSUE THREAD

**Issue by kriskoneru** [colindembovsky/ColinsALMCornerCheckinPolicies#12]
Hello, 
The issue i see is that if there are multiple code review request submitted on the same file.. for eg:- developer has submitted code review on a class file and the first code review is being done by the approver. Then the same developer submitted code review on the same class file and submitted again for code review. In the first case the code review submitted has been "Needs Work" and in the second case Code review response is "looks good" now the developer has to make changes to the first code review and the second code review is now approved. The developer wants to checkin the changes that are "looks good" but when i try to checkin the checkin policy fails saying the code review conditions are not met. which is weird.  I have to remove the work items that are failed and associate with the code review response that has been passed. Do you have any solution for this problem.

**Comment by colindembovsky** [comment]
Hi @kriskoneru - can you set the policy setting "Fail if any response needs work" to false and see if that resolves your issue?

**Comment by kriskoneru** [comment]
nope it is not working..  the main issue i see if there are multiple code review's submitted and some of them are passed and some of them are failed.. when i try to checkin in the checkin confirmation popup message it shows me "Continue to chek-in one item and resolve/assocaite 3 work items" but infact all of the work items that popup show as "Associate" but when i associate only one code review work item it doesnot take..

I am sending the screenshot if it helps.

![image](https://user-images.githubusercontent.com/16949860/27695290-73610b82-5cbc-11e7-9e01-10de9aa06b9b.png)

**Comment by colindembovsky** [comment]
Hi @kriskoneru that dialog is a Team Explorer dialog - it's got nothing to do with my Checkin Policy. It's just warning you that there are multiple work items associated with this checkin.

**Comment by kriskoneru** [comment]
yes that is correct.. but when i try to checkin it does not allow me to checkin. it still shows me the error.. 

![image](https://user-images.githubusercontent.com/16949860/27699973-2253e2b0-5cca-11e7-8d82-743da21e5a98.png)
