### ISSUE TITLE
Can't select it from the list of policies, to activate it for a team project

### ISSUE THREAD

**Issue by Nefcanto** [colindembovsky/ColinsALMCornerCheckinPolicies#13]
Hi, I installed your policies from Visual Studio Marketplace, for VS2017, from this link:

[https://marketplace.visualstudio.com/items?itemName=ColinD.ColinsALMCheckinPoliciesVS2017](https://marketplace.visualstudio.com/items?itemName=ColinD.ColinsALMCheckinPoliciesVS2017)

However, I can't see it in the list of check-in policies. Here's the path I went:
Team Explorer => Home => (from the top, click on the dropdown) => Settings => (under Team Project) Source Control => Check-in policy tab => Add => your policy name is not there.
My Visual Studio version is Community Edition, version 15.1. 

Should I activate it in another way? If so, please add a little documentation for that. 

thank you so much

**Comment by colindembovsky** [comment]
Hi @nefcanto this is the correct way to install the extension. If it's not showing, then it didn't install correctly. Can you see if there are any logs?

**Comment by colindembovsky** [comment]
Closing since there has been no update.
