### ISSUE TITLE
Policy Doesn't work for the files under immediate folder

### ISSUE THREAD

**Issue by git-anuragjain** [colindembovsky/ColinsALMCornerCheckinPolicies#14]
Policy Doesn't work for the files under immediate folder. for e.g. If I have selected path $/TestProject. 
1.) If I am updating any file under $/TestProject policy doesn't enforce me for code review.
2.) It works fine for files under any subfolder i.e. $/TestProject/FolderA

**Comment by jmelosegui** [comment]
Yeap this is a bug. @colindembovsky are you accepting PR? 
I could try to fix this.

**Comment by colindembovsky** [comment]
@jmelosegui Yes I will gladly accept PRs! Go ahead!

**Comment by git-anuragjain** [comment]
Thanks @jmelosegui and @colindembovsky for accepting and working on this to fix it,  Please update me once you fix this.

**Comment by colindembovsky** [comment]
Closed in release [3.15](https://marketplace.visualstudio.com/items?itemName=ColinD.ColinsALMCheckinPoliciesVS2017)
