### ISSUE TITLE
Trying to translate to French on TFS2015

### ISSUE THREAD

**Issue by BenoitAudet** [colindembovsky/ColinsALMCornerCheckinPolicies#20]
Hello Colin,  I'm trying to translate this policy to French and I can't seem to get the hang of it.  I just have no idea what strings the validation is looking for in a system other then english in it's validation.

Thank you

Benoit Audet

**Comment by colindembovsky** [comment]
I haven't thought about internationalizing this. However, you should be able to see the string comparisons in the code. There are a ton of them though...
