### ISSUE TITLE
Buttons still hidden related to the Issue #11

### ISSUE THREAD

**Issue by me3rag** [colindembovsky/ColinsALMCornerCheckinPolicies#21]
I am still facing the issue #11 "CheckinPolicy - bottom 4 buttons hidden",
I am using VS 2017 community v. 15.5.2. and install the extension with the version 3.15
I am also unable to resize the height of the windows

![buttons cutoff](https://user-images.githubusercontent.com/6468742/35224615-3f24a9bc-ff8e-11e7-81ef-ad31c83dea7f.JPG)

I also tries to get the latest DLL version of the 'Microsoft.TeamFoundation.VersionControl.Common' and it is 15.111.26008.0 but this DLL'Microsoft.TeamFoundation.VersionControl.Controls.Common' has the version # 14.102.25619.0

**Comment by colindembovsky** [comment]
I've updated the assembly version in 3.20. I can't repro this window not showing controls though. What is your screen resolution?

**Comment by me3rag** [comment]
Thank you Colindembovsky for your response.
My screen resolution is 1366 x 768. Sorry, this is the maximum resolution my PC providing :D 
I will also try applying the latest update to the assembly.
Thanks for you efforts.

**Comment by me3rag** [comment]
Hello Colindembovsky,
I have updated the assembly and nothing changed, the problem still exists. I think it's related to the low resolution. 
I think you can try not to dock this window or make it smaller and enable scrolling inside it may solve same low resolution screens problem.
Regards,

**Comment by colindembovsky** [comment]
I can't repro this. Even when I run at 800x600 I can still see the entire form just fine.
![image](https://user-images.githubusercontent.com/1932561/37570642-52e8fb46-2aaf-11e8-8c8f-b863bb266da9.png)
What are your scaling settings?

**Comment by me3rag** [comment]
Thank you Colindembovsky for your efforts,
Sorry for late response.

I tried to use all the available resolution on my poor machine including the 800x600 but the same result :(.
I think the problem occurs with low-resolution screens like mine.

My suggestion for you is to try not to dock this window, or make it smaller with fixed/maximum height and enable scrolling inside it.
