### ISSUE TITLE
Clicking Add button causes Code Review Policy Settings window to close/crash

### ISSUE THREAD

**Issue by slapmonkay** [colindembovsky/ColinsALMCornerCheckinPolicies#24]
Summary:
While adding or editing a Code Review Policy Setting, the default path is $\, the Remove button functions properly but when clicking Add button to select a TFS Path to select, the whole Code Review Policy Settings window closes without saving or prompting to choose a path. The net result at the end is the user's inability to change the path's that the check-in policy applies to.

Expected:
Clicking the Add button would result in showing the TFS path selector dialog, once path selected the 'Paths to apply policy to:' list box would be updated with the selected path.

Actual:
Clicking the Add button closes the Code Review Policy Settings window without saving or prompting for TFS Path.

Extra Details:
Plugin Version: 3.15
Visual Studio Version: 15.2 (26430.14) & 15.5.7
TFS Server Version: 2013

**Comment by colindembovsky** [comment]
Thanks for reporting the issue. This has been fixed in 78cf0fe0f80c0d3a228661a3b5c5f93f187a9752. In short I had to update the assembly references from 14 to 15.
