### ISSUE TITLE
Getting warning for all team members

### ISSUE THREAD

**Issue by SahithKesireddy** [colindembovsky/ColinsALMCornerCheckinPolicies#26]
Hi,
I (Project admin) have installed this plugin in my local machine (VS2017) and later I uninstalled it, but all of my team members getting the warning message "Internal error in Code Review policy, Error loading the code review policy (this policy assembly 'colinsALMCheckinPolicies.CodeReviewPolicy, Version=1.0.0.0, Culture=Neutral, PubliccKeyToken=null' is not registered.).Installation instructions: Install the extension 'colin's ALM Checkin Policies VS 2015 and VSO' from https://visualstudiogallery.msdn.microsoft.com/045730ee-63c0-498e-b972-42b05a2d0857' to get the missing policies.
Could you please tell me the resolution for this?

Thank you in advance

**Comment by colindembovsky** [comment]
Hi @SahithKesireddy - the policies are _configured_ server side (paths and settings) but _evaluated_ client-side. In other words you need to install the extension on each client machine that is required to evaluate the policy. If you install the extension on each team members' machine, the warning will go away.

**Comment by colindembovsky** [comment]
Whoops, I mis-read the question! You'll have to install the extension again, then configure it server-side and turn off the policy. Then you can uninstall the extension again.

**Comment by SahithKesireddy** [comment]
Could you please tell me how to configure it on Server-side?

**Comment by colindembovsky** [comment]
"Server side" just means Check-in policies. From Team Explorer, select the Settings page, then select Source Control under the Project section. Click the Check-in Policy tab and then delete or disable the Code Review checkin policy.

**Comment by SahithKesireddy** [comment]
Thank you so much for the response and am verifying it and will update you.

**Comment by SahithKesireddy** [comment]
Thank you so much and it worked.
