### ISSUE TITLE
Possible feature request:  Ignore Abandoned Reviews

### ISSUE THREAD

**Issue by jgrinwaldDartChart** [colindembovsky/ColinsALMCornerCheckinPolicies#5]
In our TFS setup, once a reviewer uses "Send & Finish" to complete their review with a "Needs Work", nothing can be done by either the requestor or reviewer that will allow that "Send & Finish" response to be altered, and the review then prevents check-in unless an override is done. An added option to the check-in policy to ignore Abandoned reviews would allow the Requestor to close the Review as "Abandoned", and then make changes and request a new Review.

**Comment by punitganshani** [comment]
+1

**Comment by jmelosegui** [comment]
@jgrinwaldDartChart  What if you just remove the Code Review work item from the list of associated ones?

I think that should let you check-in your changes.

**Comment by colindembovsky** [comment]
Closed in release [3.15](https://marketplace.visualstudio.com/items?itemName=ColinD.ColinsALMCheckinPoliciesVS2017). I think that the "Check only most recent Request" solves this issue.
