### ISSUE TITLE
Changes History

### ISSUE THREAD

**Issue by Cassandra-d** [colindembovsky/ColinsALMCornerCheckinPolicies#6]
Hi.
Is it possible to have Changes History somewhere?
I saw that there is a new version of Checkin Policies and I can't find info about what has been changed.
Or I just missed it?
Thanks.

**Comment by colindembovsky** [comment]
Closed in release [3.15](https://marketplace.visualstudio.com/items?itemName=ColinD.ColinsALMCheckinPoliciesVS2017)
