### ISSUE TITLE
Cannot add or change path

### ISSUE THREAD

**Issue by shannonpower** [colindembovsky/ColinsALMCornerCheckinPolicies#9]
Using VS 2017 Community I cannot modify or add a new source control path to apply a code review policy. The Add and Remove buttons in the dialog are cutoff and when using TAB to highlight Add, the dialog just disappears. Any ideas? Thanks

**Comment by PaytonWu** [comment]
solution: update Microsoft.TeamFoundation.VersionControl.Controls.Common.dll in the VSIX package.  This DLL maybe locates under "ProgramFilesPath\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer".  In fact all the DLLs listed in the VSIX can be found under this folder.

**Comment by tekkenxpert** [comment]
Hi @PaytonWu 

You mentioned to update the Microsoft.TeamFoundation.VersionControl.Controls.Common.dll, but did not provide the version or replacement dll. Currently showing version 15.117.26914.0

**Comment by PaytonWu** [comment]
![2017-12-17](https://user-images.githubusercontent.com/2065762/34077409-7faa0c32-e33e-11e7-886f-8e9af4b362b2.png)
@tekkenxpert 
sorry for the late response.  The attached screenshot is what I used when I providing the solution.  I think the version you mentioned should also work.  In fact, I just used those Dlls on my PC and re-packaged this extension, and verified that it worked (I'm now using VS 15.5.  The version of those Dlls on my PC has changed to 15.123.27127.4 and the installed extension still works).

But my local solution doesn't resolve #11 on high-resolution screen.  The best solution is to clone this repro, update the code, use your local VS DLLs and re-generate this extension.

**Comment by colindembovsky** [comment]
Closed in release [3.15](https://marketplace.visualstudio.com/items?itemName=ColinD.ColinsALMCheckinPoliciesVS2017)

**Comment by tekkenxpert** [comment]
Dialog is fixed and buttons are no longer cutoff, however when clicking 'Add' to add a new source path the dialog just goes away.

**Comment by buddde** [comment]
Same for me: clicking on Add makes the dialog fade away
